require "luax"

local function _print(first, second)
  print(tostring(first) .. "\t" .. tostring(second))
end

print("--[[Array]]--")
_print("type(Array)", type(luax.Array))
local array = luax.Array:new(1, 2, 3, 4, 5, 6, 7, 8, 9)
_print("Array:new()", array)
_print("Array:pushfirst()", array:copy():pushfirst("0"))
_print("Array:pushlast()", array:copy():pushlast("10"))
_print("Array:popfirst()", array:copy():popfirst())
_print("Array:poplast()", array:copy():poplast())
_print("Array:first()", array:first())
_print("Array:last()", array:last())
_print("Array:each()", array:each(function (v) return v end))
_print("Array:all(<10)", array:all(function (v) return v < 10 end))
_print("Array:count(<10)", array:count(function (v) return v < 10 end))
_print("Array:any(<10)", array:any(function (v) return v < 10 end))
_print("Array:none(<10)", array:none(function (v) return v < 10 end))
_print("Array:contains(10)", array:contains(10))
_print("Array:map('_' + v)", array:copy():map(function (v) return "_" .. v end))
_print("Array:filter(v%2==0)", array:filter(function (v) return tonumber(v) % 2 == 0 end))
_print("Array:split(5)", array:split(5))
_print("Array:invert()", array:invert())
_print("Array:remove(1)", array:copy():remove(1))
_print("Array:clear()", array:clear())

print("--[[Class]]--")
_print("type(Class)", type(Class))
_print("Class:constructor(...)", function (...) end)
local Animal = luax.Class:new("Animal")
function Animal:constructor(planet)
  self.planet = planet or "earth"
end
local animal = Animal()
_print("Animal=Class:new('Animal')", "")
local Dog = Animal:extend("Dog")
_print("Dog=Animal:extend('Dog')", "")
local anyDog = Dog()
_print("anyDog=Dog()", anyDog)
local myDog = Dog()
_print("myDog=Dog()", myDog)
_print("myDog.super", myDog.super)
local Alien = Animal:extend("Alien")
_print("Alien=Animal:extend('Alien')", "")
local alien = Alien("pluto")
_print("alien=Alien('pluto')", alien)
_print("myDog:is(Alien)", myDog:is(Alien))
_print("alien:is(Animal)", alien:is(Animal))
_print("alien.planet", alien.planet)

print("--[[Fifo]]--")
local fifo = luax.Fifo(2)
_print("Fifo(2)", fifo)
fifo:push(1)
_print("fifo:push(1)", fifo)
fifo:push(2)
_print("fifo:push(2)", fifo)
fifo:push(3)
_print("fifo:push(3)", fifo)
fifo:clear()
_print("fifo:clear()", fifo)

print("--[[Log]]--")
_print("Log.FILENAME", luax.Log.FILENAME)
_print("Log.FILE", luax.Log.FILE)
_print("Log.verbose(...)", luax.Log.verbose)
_print("Log.debug(...)", luax.Log.debug)
_print("Log.info(...)", luax.Log.info)
_print("Log.warning(...)", luax.Log.warning)
_print("Log.error(...)", luax.Log.error)
_print("Log.wtf(...)", luax.Log.wtf)
_print("Log.close()", luax.Log.close)

print("--[[Path]]--")
_print("Path.root", luax.Path.root)
_print("Path.dirname(Path.root)", luax.Path.dirname(luax.Path.root))
_print("Path.basename(Path.root)", luax.Path.basename(luax.Path.root))
_print("Path.split(Path.root)", luax.Path.split(luax.Path.root))

print("--[[Utils]]--")
_print("tostring({...})", tostring({"a", "b", "c"}))
_print("loop(2,f(i))", "")
luax.loop(2, function (i) _print("", i) end)
_print("lines('hello\\nworld')", luax.lines("hello\nworld"))
_print("lines('hello world', ' ')", luax.lines("hello\nworld", " "))
_print("math.randomseed", math.randomseed)
_print("randomboolean()", luax.randomboolean())
_print("randomtable({1,2,3})", luax.randomtable({1, 2, 3}))
_print("math.clamp(10,1,9)", math.clamp(10, 1, 9))
_print("math.sign(10)", math.sign(-10))

print("--[[Version]]--")
local oldVersion = luax.Version(1,2,3)
_print("oldVersion=Version(1,2,3)", oldVersion)
_print("oldVersion.major", oldVersion.major)
_print("oldVersion.minor", oldVersion.minor)
_print("oldVersion.patch", oldVersion.patch)
local newVersion = luax.Version(3,2,1)
_print("newVersion=Version(3,2,1)", newVersion)
_print("newVersion<oldVersion", newVersion < oldVersion)
_print("newVersion>oldVersion", newVersion > oldVersion)
_print("oldVersion==newVersion", oldVersion == newVersion)
_print("newVersion==newVersion", newVersion == newVersion)
